***1.WHAT IS EMBEDDINGS?***


- Embedings are numerical repreentations of text,images,audio, or any data. For text(usually our focus), and embedding is:

    - A vector(long list of numbers)
    - Generated by a model
    - Designed so that similar meanings-> similar numbers

***2.WHY USE EMBEDDINGS?***

- Because computers don't understand text directly- they iunderstand numbers

- Embeddings allows system to:

    - search semantically("meaning based search")
    - Build recommendation systems
    - measure similarity between texts
    - Cluster documents
    - RAG(Retrieval-Augmented Generation),including chatgroq workflows


***3.WHAT IS A SIMILARITYY SCORE?***

- once you have embeddings, you measure similarity using a mathematical formula
- The mosr common one is:
**cosine sililarity**
it measures the angle between two vectors
    - 1.0-> identical meaning
    - 0.0-> unrwelated
    - 1.0-> opposite meaning

In [1]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [9]:
import warnings
warnings.filterwarnings('ignore')
model = SentenceTransformer("all-MiniLM-L6-v2")

In [10]:
sentences = [
    "I like apples.",
    "I enjoy eating apples.",
    "I drive a motorcycle."
]
    

In [15]:
embeddings = model.encode(sentences)

In [17]:
embeddings

array([[-0.00795679,  0.00439061,  0.00202515, ...,  0.05261279,
         0.09204272,  0.01492958],
       [ 0.04228426, -0.02286868,  0.01099179, ...,  0.04014789,
         0.01113548, -0.02590688],
       [ 0.00638027,  0.02684815,  0.01856962, ...,  0.05433165,
        -0.02654601, -0.11293565]], dtype=float32)

In [19]:
embeddings[0]

array([-7.95678701e-03,  4.39060619e-03,  2.02515326e-03,  4.47825640e-02,
       -4.11381647e-02, -1.17856069e-02,  9.93528441e-02, -1.49924774e-02,
        3.28452550e-02,  2.80843787e-02,  3.82004939e-02, -3.95743959e-02,
        3.20650302e-02, -1.52864512e-02,  3.38638499e-02,  7.11711636e-03,
        6.39917180e-02, -4.05894741e-02, -4.73222211e-02, -1.12335552e-02,
       -7.96146840e-02,  7.19405115e-02,  5.19621596e-02, -1.93749629e-02,
        9.35396820e-04,  4.32007723e-02,  1.97203048e-02, -3.00485939e-02,
       -8.23600665e-02, -3.70824374e-02, -5.02395220e-02,  1.10582998e-02,
        2.05313545e-02,  1.45488130e-02, -3.76088843e-02,  1.48733342e-02,
        1.00732088e-01, -3.48994248e-02, -2.48851851e-02, -1.85873248e-02,
        1.62230560e-03,  5.87751344e-02,  5.86785935e-02,  5.20198047e-02,
       -5.73277585e-02, -1.06776031e-02,  3.00519653e-02, -4.60932888e-02,
        9.38398466e-02,  5.82441725e-02,  6.42052516e-02, -9.02686385e-04,
       -4.48686108e-02, -

In [21]:
len(embeddings[0])

384

In [33]:
v1=embeddings[0].reshape(-1,1)
v2=embeddings[1].reshape(-1,1)
v3=embeddings[2].reshape(-1,1)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
cosine_similarity(v1,v2)

array([[-1.,  1., -1., ..., -1., -1.,  1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       ...,
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.]], dtype=float32)

In [39]:
def cosine_sum(a,b):
    return np.dot(a,b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [41]:
v1=embeddings[0]
v2=embeddings[1]
cosine_sum(v1,v2)

0.837434